name: Auto Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 1 phút

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3  # Cập nhật từ v2 lên v3

    - name: Commit changes
      run: |
        git config --local user.email "humhliao@gmail.com"
        git config --local user.name "humhliao"
        git add .
        git commit -m "Auto commit" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
