name: Auto Commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Chạy mỗi 5 phút

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Set up Git configuration
      run: |
        git config --local user.email "humhliao@gmail.com"
        git config --local user.name "humhliao"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Auto commit" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
